### ISSUE TITLE
Ignore pkgsnap package

### ISSUE THREAD

**Issue by dougmet** [MangoTheCat/pkgsnap#5]
Either ignore or at least handle separately. If the recorded version doesn't match the installed version it could give a warning, if it does match then it should be skipped.

Should it attempt to bootstrap itself if the installed version doesn't match the recorded? I would suggest that's a future feature.

**Comment by gaborcsardi** [comment]
Ignoring it in restore makes sense, people need to have it installed if they are calling restore... I don't think we need to worry much about the version, at least not until we change the data format.

Somewhat related, I was also thinking about rewriting the whole stuff a shell script, a lot more painful to write, of course, but then these problems pretty much go away. You do need to share the shell script, though. Or merge the package list with the shell script.

**Comment by dougmet** [comment]
From a provisioning point of view that is probably ideal (and potentially more unique in the package version space). I'm not a big fan of merging the script and the package inventory. The latter makes a useful record in a repository.

**Comment by gaborcsardi** [comment]
Good point about (not) merging. Anyway, I think for now we can just ignore it when restoring.
